chore: support large wasm in orbit script

diff --git a/orbit b/orbit
--- a/orbit
+++ b/orbit
@@ -17,6 +17,15 @@ CANISTER_ID_INTERNET_IDENTITY="rdmx6-jaaaa-aaaaa-aaadq-cai"
 CANISTER_ID_UI="werw6-ayaaa-aaaaa-774aa-cai"
 CANISTER_ID_WALLET="wkt3w-3iaaa-aaaaa-774ba-cai"
 
+# Default identity store path
+DFX_DEFAULT_IDENTITY_STORE_PATH=${DFX_DEFAULT_IDENTITY_STORE_PATH:-"$HOME/.config/dfx/identity"}
+
+# Identity PEM path to use for the deployment of the asset canister files
+IDENTITY_PEM_PATH=${IDENTITY_PEM_PATH:-""}
+
+# Path to the dfx.json file
+DFX_JSON_PATH=${DFX_JSON_PATH:-"dfx.json"}
+
 #############################################
 # USAGE                                     #
 #############################################
@@ -154,19 +163,47 @@ function uninstall_control_panel() {
 }
 
 function install_control_panel() {
+  if ! command -v icx-asset >/dev/null 2>&1; then
+    echo "icx-asset not found, installing..."
+
+    cargo install icx-asset --version 0.21.0
+
+    echo "icx-asset installed successfully."
+
+  fi
+
+  identity=$(dfx identity whoami)
+
+  if [ -z "$identity" ]; then
+    echo "No identity found, please login to your dfx environment."
+    exit 1
+  fi
+
+  echo "Current identity: $identity"
+  echo
+    
+  set_identity_pem_path "$identity"
+
   # Builds the dependencies and generates the WASM files
   build_wasm upgrader
   build_wasm station
 
   # Read the WASM files and convert them to hex format
   upgrader_wasm_module_bytes=$(hexdump -ve '1/1 "%.2x"' ./wasms/upgrader.wasm.gz | sed 's/../\\&/g')
-  station_wasm_module_bytes=$(hexdump -ve '1/1 "%.2x"' ./wasms/station.wasm.gz | sed 's/../\\&/g')
+  station_wasm_module_hash=$(sha256sum ./wasms/station.wasm.gz | grep -o "^[0-9a-z]*" | sed 's/../\\&/g')
+
+  dfx canister create wasm_chunk_store --no-wallet
+  dfx build wasm_chunk_store
+  dfx canister install wasm_chunk_store
+  wasm_chunk_store_id=$(dfx canister id wasm_chunk_store)
+
+  icx-asset --pem $IDENTITY_PEM_PATH --replica $(get_replica_url) upload $wasm_chunk_store_id ./wasms/station.wasm.gz
 
   dfx canister create --specified-id $CANISTER_ID_CONTROL_PANEL control_panel
   dfx build control_panel
   dfx canister install control_panel
   dfx canister call control_panel upload_canister_modules --argument-file <(echo "(record { upgrader_wasm_module = opt blob \"$upgrader_wasm_module_bytes\"; station_wasm_module = null; })")
-  dfx canister call control_panel upload_canister_modules --argument-file <(echo "(record { upgrader_wasm_module = null; station_wasm_module = opt blob \"$station_wasm_module_bytes\"; })")
+  dfx canister call control_panel upload_canister_modules --argument-file <(echo "(record { upgrader_wasm_module = null; station_wasm_module = null; station_wasm_module_extra_chunks = opt opt record { store_canister = principal\"$(dfx canister id wasm_chunk_store)\"; extra_chunks_key = \"/station.wasm.gz\"; wasm_module_hash = blob\"$station_wasm_module_hash\" } })")
 }
 
 function setup_control_panel() {
@@ -223,6 +260,68 @@ function approve_waiting_list() {
   local principal=$1
 
   dfx canister call control_panel update_waiting_list "record { users = vec { principal \"$principal\" }; new_status = variant {Approved} }"
+}
+
+#############################################
+# UTILS                                     #
+#############################################
+
+function get_network() {
+  local network=${IC_NETWORK:-local}
+  echo "$network"
+}
+
+function get_replica_url() {
+  local network=$(get_network)
+  local result
+
+  # Extract the first provider or bind using jq
+  result=$(jq -r --arg network "$network" \
+    '.networks[$network] |
+    if .providers then .providers[0]
+    elif .bind then "http://" + .bind
+    else null
+    end' "$DFX_JSON_PATH")
+
+  if [ -z "$result" ] || [ "$result" == "null" ]; then
+    echo -e "\e[1;31m"
+    echo "ERROR: Replica URL not found for the network: $network"
+    echo "Please make sure the dfx.json file is correctly configured."
+    echo -e "\e[0m"
+
+    exit 1
+  else
+    echo "$result"
+  fi
+}
+
+function set_identity_pem_path() {
+  local identity_name=$1
+  local identity_store_path=${DFX_DEFAULT_IDENTITY_STORE_PATH}
+
+  if [ -z "$IDENTITY_PEM_PATH" ]; then
+    local identity_pem_path="${identity_store_path}/${identity_name}/${identity_name}.pem"
+
+    # Check if the identity pem file exists, else fallback to the id.pem filename
+    if [ ! -f "$identity_pem_path" ]; then
+      identity_pem_path="${identity_store_path}/${identity_name}/identity.pem"
+    fi
+
+    if [ ! -f "$identity_pem_path" ]; then
+      identity_pem_path="${identity_store_path}/${identity_name}/id.pem"
+    fi
+
+    export IDENTITY_PEM_PATH=$identity_pem_path
+  fi
+
+  if [ ! -f "$IDENTITY_PEM_PATH" ]; then
+    echo -e "\e[1;31m"
+    echo "ERROR: Identity PEM file not found for the identity: $identity_name"
+    echo "Please make sure the identity is available in the default identity store path: $identity_store_path"
+    echo -e "\e[0m"
+
+    exit 1
+  fi
 }
 
 #############################################
